// Package bpf exposes the kernel↔userspace ABI for the telemetry agent.
//
// The map specs and loader are generated by bpf2go from bpf/telemetry.c
// into telemetry_bpfel.go under unexported names; abi.go and schema.go
// are the package's only public surface.
//
// Everything here must stay in lockstep with bpf/telemetry.c — the
// layouts and constants cross the kernel boundary, and silent skew
// corrupts metrics rather than failing loudly. Never hand-copy a
// generated struct layout.
//
// The ABI types are imported from every layer on purpose; that is not a
// layering violation. See
// docs/development/conventions.md#layering-and-the-bpf-abi
package bpf

import (
	"encoding/binary"
	"fmt"
	"net/netip"

	"github.com/cilium/ebpf"
)

// MACKey packs a 6-byte MAC into the low 48 bits of a u64, big-endian.
// Mirrors the C-side `mac_to_u64` in bpf/telemetry.c — both sides
// must agree exactly, or `mac_tenant_map` lookups will silently miss.
// `mac[0]` is the OUI / most-significant byte, `mac[5]` the least.
func MACKey(mac [6]uint8) uint64 {
	return uint64(mac[0])<<40 | uint64(mac[1])<<32 |
		uint64(mac[2])<<24 | uint64(mac[3])<<16 |
		uint64(mac[4])<<8 | uint64(mac[5])
}

// LpmKeyForPrefix builds an [LpmKey] for the kernel subnet_zone_trie
// from an interned tenant ID and an IPv4 prefix. Prefixlen is
// [LpmKeyTenantBits] plus the prefix bits: the kernel exact-matches the
// tenant before walking the address.
//
// Ip holds WIRE byte order, not host order. The trie walks key bytes
// MSB-first, so the IPv4 address must lead with its MSB in memory;
// NativeEndian over As4() gives that on either endianness, and the C
// side assigns the wire value with no ntohl. Changing either half
// silently breaks CIDR matching.
//
// Panics on an IPv6 prefix — the trie is IPv4-only and callers filter
// upstream.
func LpmKeyForPrefix(tenantID uint32, prefix netip.Prefix) LpmKey {
	addr := prefix.Addr()
	if !addr.Is4() {
		panic(fmt.Sprintf("LpmKeyForPrefix: IPv6 prefix unsupported: %s", prefix))
	}
	bytes := addr.As4()
	return LpmKey{
		Prefixlen: LpmKeyTenantBits + uint32(prefix.Bits()),
		TenantId:  tenantID,
		Ip:        binary.NativeEndian.Uint32(bytes[:]),
	}
}

// AmphoraKeyForIP builds the `amphora_base_ip` key for one Amphora
// address. tenantID is the interned id of the load balancer's owner —
// masked, i.e. WITHOUT the [TenantAmphoraFlag] the mac_tenant_map value
// carries, because the kernel masks before probing this map.
//
// The IP is encoded in wire (network) byte order, matching how the
// classifier passes iph->saddr / iph->daddr straight through. Panics on
// an IPv6 address: the kernel path is IPv4-only, same contract as
// [LpmKeyForPrefix].
func AmphoraKeyForIP(tenantID uint32, addr netip.Addr) AmphoraKey {
	if !addr.Is4() {
		panic(fmt.Sprintf("AmphoraKeyForIP: IPv6 address unsupported: %s", addr))
	}
	bytes := addr.As4()
	return AmphoraKey{
		TenantId: tenantID,
		Ip:       binary.NativeEndian.Uint32(bytes[:]),
	}
}

// LoadTelemetry returns the CollectionSpec for the telemetry BPF program,
// ready to be loaded into the kernel.
func LoadTelemetry() (*ebpf.CollectionSpec, error) {
	return loadTelemetry()
}

// ValidateMapSizes checks every compiled `max_entries` against its
// Go-side constant. A mismatch means a stale BPF object — usually a
// size bumped without `task generate` — so the agent refuses to start
// rather than write into a wrongly-sized map. For telemetry_stats the
// size is the stat-reason count, so this also pins the C enum to its Go
// mirror. Returns a multi-line error naming every mismatch.
func ValidateMapSizes(spec *ebpf.CollectionSpec) error {
	if spec == nil {
		return fmt.Errorf("bpf: ValidateMapSizes called with nil spec")
	}
	type check struct {
		name string
		want uint32
	}
	var problems []string
	for _, c := range []check{
		{MapTelemetry, MapTelemetryMaxEntries},
		{MapMacTenant, MapMacTenantMaxEntries},
		{MapSubnetZoneTrie, MapSubnetZoneTrieMaxEntries},
		{MapTelemetryStats, MapTelemetryStatsMaxEntries},
		{MapAmphoraBaseIP, MapAmphoraBaseIPMaxEntries},
	} {
		m, ok := spec.Maps[c.name]
		if !ok {
			problems = append(problems, fmt.Sprintf("%s: not present in spec", c.name))
			continue
		}
		if m.MaxEntries != c.want {
			problems = append(problems,
				fmt.Sprintf("%s: spec.MaxEntries=%d, want %d (Go-side authority)",
					c.name, m.MaxEntries, c.want))
		}
	}
	if len(problems) == 0 {
		return nil
	}
	return fmt.Errorf("bpf: map-size drift (run `task generate`): %v", problems)
}
